### ISSUE TITLE
Github App Credentials not being passed to getAuthHeader function

### ISSUE THREAD

**Issue by eliot-pitman-bah** [samsmithnz/lead-time-for-changes#32]
Looks like the appId, appInstallationId, and appPrivateKey are not getting passed to the getAuthHeader function, resulting in "No authentication detected"

https://github.com/DeveloperMetrics/lead-time-for-changes/blob/main/src/leadtimeforchanges.ps1#L47 

Let me know if I overlooked something.

Thanks!

**Comment by samsmithnz** [comment]
You are absolutely right - how odd that I missed this - it's right there in it's sister project [deployment frequency](https://github.com/DeveloperMetrics/deployment-frequency/blob/c23f44474a3416c2e09ff8b3b5cde52d0d2d7ce5/src/deploymentfrequency.ps1#L40C56-L40C97)!

I'll push a fix shortly. Thanks for identifying this!
